### ISSUE TITLE
Menu not responsive

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/foliogine#7]
While the menu is suppose to be responsive, it is not. There is some sort of JS issue which is breaking the responsive menu.

Same with the lite version :)

@ineagu

**Comment by HardeepAsrani** [comment]
@ineagu This is a pretty big bug, and I think it should get some priority. If it's a jQuery conflict-ion then it shouldn't be difficult for someone who knows jQuery :)

**Comment by ineagu** [comment]
@rodica-andronache can you take a look at this ? for both lite and pro ?
